# Copyright (C) 2015
# Author: Ali Paikan
# CopyPolicy: Released under the terms of the GNU GPL v2.0.

# Jan 2011. It is time to add versioning information to the Cuddie builds.

set(CUDDIE_VERSION_MAJOR "1")
set(CUDDIE_VERSION_MINOR "0")
set(CUDDIE_VERSION_PATCH "0")
set(CUDDIE_VERSION_MODIFIER "")
set(CUDDIE_VERSION_ABI "0")

set(CPACK_PACKAGE_VERSION_MAJOR "${CUDDIE_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CUDDIE_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CUDDIE_VERSION_PATCH}${CUDDIE_VERSION_MODIFIER}")

set(CUDDIE_GENERIC_VERSION "${CUDDIE_VERSION_MAJOR}.${CUDDIE_VERSION_MINOR}.${CUDDIE_VERSION_PATCH}")
set(CUDDIE_GENERIC_SOVERSION "${CUDDIE_VERSION_ABI}")
